### ISSUE TITLE
Possible sysinfo exception when there are open files on different drives

### ISSUE THREAD

**Issue by ritsu** [ritsu/RitsuCogs#8]
```
Collecting psutil
  Using cached psutil-5.2.2-cp35-cp35m-win32.whl
Installing collected packages: psutil
Successfully installed psutil-5.2.2
Copying sysinfo...
[18/06/2017 18:00] ERROR red on_command_error 369: Exception in command 'sysinfo'
Traceback (most recent call last):
  File "lib\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "G:\Software\Red-DiscordBot\cogs\sysinfo.py", line 62, in psutil
    common = os.path.commonpath([f.path for f in open_f])
  File "G:\Software\Python35-32\lib\ntpath.py", line 632, in commonpath
    raise ValueError("Paths don't have the same drive")
ValueError: Paths don't have the same drive
```

**Comment by ritsu** [comment]
Fixed in https://github.com/ritsu/RitsuCogs/pull/9
